name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Setup SSH access to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy frontend
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /opt/itbem-events-frontend
            git pull origin ${{ github.event.inputs.branch || 'main' }}
            docker stop itbem-events-frontend || true && docker rm itbem-events-frontend || true

            docker build -t itbem-events-frontend . \
              --build-arg EVENTS_URL=${{ secrets.EVENTS_URL }} \
              --build-arg REDIS_URL=${{ secrets.REDIS_URL }}

            docker run -d --name itbem-events-frontend \
              --restart always \
              -p 4321:4321 \
              -e PORT=4321 \
              -e PUBLIC_EVENTS_URL=${{ secrets.EVENTS_URL }} \
              -e PUBLIC_REDIS_URL=${{ secrets.REDIS_URL }} \
              itbem-events-frontend
          EOF
